Listen 5003

ServerName stapp02.stratos.xfusioncorp.com

LoadModule headers_module modules/mod_headers.so

Header set X-XSS-Protection "1; mode=block"
Header always append X-Frame-Options SAMEORIGIN
Header set X-Content-Type-Options nosniff

IncludeOptional conf.d/*.conf
